### ISSUE TITLE
lab4.1 Gauss-Legendre has some problems,

### ISSUE THREAD

**Issue by houdezaiwu2019** [RichardoML/NumericalAnalysis2021-postgraduate#1]

**Comment by RichardoML** [comment]
已收到

**Comment by houdezaiwu2019** [comment]
You right, Thank you

**Comment by houdezaiwu2019** [comment]
But the report can not open when I download it to my penson computer.

**Comment by RichardoML** [comment]
不是吧，我自己下下来很正常啊，

**Comment by RichardoML** [comment]
> 



> But the report can not open when I download it to my penson computer.

我自己下下来很正常啊

**Comment by houdezaiwu2019** [comment]
好的，我WPS试试，可能我word的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月26日(星期四) 中午1:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RichardoML/NumericalAnalysis2021-postgraduate] lab4.1 Gauss-Legendre has some problems, (Issue #1)





 
不是吧，我自己下下来很正常啊，

**Comment by RichardoML** [comment]
已收到
